from __future__ import annotations

import os
import uuid
import json
from typing import Dict, Any, Optional
from datetime import datetime

from backend.config.app_config import settings


class ModelService:
    def __init__(self):
        self.models: Dict[str, Dict] = {}
        self.static_dir = settings.static_files_dir
        self.models_dir = settings.models_dir

    async def generate_model(
        self,
        parameters: Dict[str, Any],
        format: str = "obj",
        optimize: bool = True,
        resolution: str = "medium",
    ) -> Dict[str, Any]:
        """生成3D模型"""
        model_id = str(uuid.uuid4())

        model_data = {
            'model_id': model_id,
            'parameters': parameters,
            'format': format,
            'optimize': optimize,
            'resolution': resolution,
            'created_at': datetime.now().isoformat(),
            'status': 'generated',
        }

        self.models[model_id] = model_data

        os.makedirs(self.models_dir, exist_ok=True)
        model_file = os.path.join(self.models_dir, f'{model_id}.{format}')

        model_content = self._generate_model_content(parameters, format)

        with open(model_file, 'w') as f:
            f.write(model_content)

        url = f'/static/models/{model_id}.{format}'

        return {
            'model_id': model_id,
            'url': url,
            'format': format,
            'vertices': self._count_vertices(parameters),
            'triangles': self._count_triangles(parameters),
        }

    def _generate_model_content(self, parameters: Dict[str, Any], format: str) -> str:
        """生成模型内容"""
        if format == 'obj':
            return self._generate_obj_content(parameters)
        elif format == 'gltf':
            return self._generate_gltf_content(parameters)
        elif format == 'stl':
            return self._generate_stl_content(parameters)
        else:
            raise ValueError(f"Unsupported format: {format}")

    def _generate_obj_content(self, parameters: Dict[str, Any]) -> str:
        """生成OBJ格式内容"""
        lines = ['# Generated by Aircraft Design ChatUI']
        lines.append('# Vertices')
        lines.append(f'v {self._count_vertices(parameters)}')

        for i in range(self._count_vertices(parameters)):
            lines.append(f'v {i} 0.0 0.0 0.0')

        lines.append('# Faces')
        lines.append(f'f {self._count_triangles(parameters)}')

        for i in range(self._count_triangles(parameters)):
            lines.append(f'f {i} {i} {i+1} {i+2}')

        return '\n'.join(lines)

    def _generate_gltf_content(self, parameters: Dict[str, Any]) -> str:
        """生成GLTF格式内容"""
        import json

        gltf_data = {
            "asset": {
                "version": "2.0",
                "generator": "Aircraft Design ChatUI"
            },
            "scene": 0,
            "nodes": self._count_vertices(parameters),
            "meshes": [
                {
                    "primitives": [
                        {
                            "attributes": {},
                            "indices": list(range(self._count_triangles(parameters) * 3)),
                            "mode": 0
                        }
                    ]
                }
            ]
        }

        return json.dumps(gltf_data, indent=2)

    def _generate_stl_content(self, parameters: Dict[str, Any]) -> str:
        """生成STL格式内容"""
        lines = [
            f'solid {parameters.get("name", "model")}',
            f'facet normal {0.0} {0.0} {1.0}',
            f'  outer loop',
            f'    vertex {0.0} {0.0} {0.0}',
            f'    vertex {1.0} {0.0} {0.0}',
            f'    vertex {0.0} {1.0} {0.0}',
            f'  endloop',
        ]

        for i in range(self._count_triangles(parameters)):
            lines.extend([
                f'facet normal {0.0} {0.0} {1.0}',
                f'  outer loop',
                f'    vertex {i} {i} {i+1}',
                f'    vertex {i+1} {i} {i+1}',
                f'    vertex {i} {i+1} {i}',
                f'  endloop',
            ])

        lines.append(f'endsolid {parameters.get("name", "model")}')

        return '\n'.join(lines)

    def _count_vertices(self, parameters: Dict[str, Any]) -> int:
        """计算顶点数量"""
        return parameters.get('vertices', 100)

    def _count_triangles(self, parameters: Dict[str, Any]) -> int:
        """计算三角形数量"""
        return parameters.get('triangles', 50)

    def get_model(self, model_id: str) -> Optional[Dict[str, Any]]:
        """获取3D模型"""
        return self.models.get(model_id)

    def delete_model(self, model_id: str) -> bool:
        """删除3D模型"""
        if model_id not in self.models:
            return False

        del self.models[model_id]

        model_file = os.path.join(self.models_dir, f'{model_id}.obj')
        if os.path.exists(model_file):
            os.remove(model_file)

        return True

    def list_models(self) -> Dict[str, Dict[str, Any]]:
        """列出所有3D模型"""
        return self.models

    def export_model(self, model_id: str, format: str = "obj") -> Dict[str, Any]:
        """导出3D模型"""
        model = self.get_model(model_id)
        if not model:
            raise ValueError(f"Model {model_id} not found")

        model_file = os.path.join(self.models_dir, f'{model_id}.{format}')

        if not os.path.exists(model_file):
            raise ValueError(f"Model file {model_file} not found")

        url = f'/static/models/{model_id}.{format}'

        return {
            'url': url,
            'format': format,
        }


global_model_service = ModelService()
